apps:
  - script: ./app/index.js
    name: 'knck'
    env:
      NODE_ENV: production
      HOST: '0.0.0.0'
      PORT: 5000
      #AWS_REGION: {required}
      #AWS_ACCESS_KEY_ID: {required}
      #AWS_SECRET_ACCESS_KEY: {required}
      #DB_ITEM_TTL: {optional}
